import React from 'react'

const files = [
  { name: 'cat_in_space.png', color: '#1e40af' },
  { name: 'extracted_text.txt', color: '#047857' },
  { name: 'social_posts.json', color: '#be185d' },
]

export default function FilesSection() {
  return (
    <div className="workspace-section">
      <div className="workspace-header">
        <h1>Shared Library (S3 Bucket)</h1>
        <p>All files generated by microservices are saved here.</p>
      </div>
      <div className="results-grid">
        {files.map(file => (
          <div key={file.name} className="result-item filled" style={{ backgroundColor: file.color }}>
            {file.name}
          </div>
        ))}
      </div>
    </div>
  )
}
